version: '3'
services:

  cpms:
    build:
      context: ./cpms
      dockerfile: Dockerfile
    environment:
      #      - DB_URL=jdbc:postgresql://host.docker.internal:5432/icms_db
      - DB_URL=jdbc:postgresql://postgres:5432/icms_db
      - DB_USER=icms_app
      - DB_PASSWORD=3211
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USER=icms_app
      - RABBITMQ_PASSWORD=3211
      - DOWNLOADER_MOUNT_POINT=./
      - QUEUE_CPMS_NAME=icms.cpms
      - LOG_LEVEL=debug
    depends_on:
      - postgres
      - migrations
      - rabbitmq
    networks:
      - icms-network


  downloader:
    build:
      context: ./downloader
      dockerfile: Dockerfile
    environment:
#      - DB_URL=jdbc:postgresql://host.docker.internal:5432/icms_db
      - DB_URL=jdbc:postgresql://postgres:5432/icms_db
      - DB_USER=icms_app
      - DB_PASSWORD=3211
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USER=icms_app
      - RABBITMQ_PASSWORD=3211
      - DOWNLOADER_MOUNT_POINT=/app/data
      - QUEUE_DOWNLOADER_NAME=icms.downloader
      - QUEUE_CPMS_NAME=icms.cpms
      - QUEUE_SCHEDULER_RESPONSE_NAME=icms.scheduler-response
      - LOG_LEVEL=debug
    volumes:
      - /tmp/ISMC_STORAGE:/app/data
    depends_on:
      - postgres
      - migrations
      - rabbitmq
    networks:
      - icms-network


  importer:
    build:
      context: ./importer
      dockerfile: Dockerfile
    environment:
      #      - DB_URL=jdbc:postgresql://host.docker.internal:5432/icms_db
      - DB_URL=jdbc:postgresql://postgres:5432/icms_db
      - DB_USER=icms_app
      - DB_PASSWORD=3211
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USER=icms_app
      - RABBITMQ_PASSWORD=3211
      - DOWNLOADER_MOUNT_POINT=/app/data
      - QUEUE_IMPORTER_NAME=icms.importer
      - QUEUE_CPMS_NAME=icms.cpms
      - QUEUE_SCHEDULER_RESPONSE_NAME=icms.scheduler-response
      - LOG_LEVEL=debug
    volumes:
      - /tmp/ISMC_STORAGE:/app/data
    depends_on:
      - postgres
      - migrations
      - rabbitmq
    networks:
      - icms-network


  scheduler:
    build:
      context: ./scheduler
      dockerfile: Dockerfile
    environment:
      #      - DB_URL=jdbc:postgresql://host.docker.internal:5432/icms_db
      - DB_URL=jdbc:postgresql://postgres:5432/icms_db
      - DB_USER=icms_app
      - DB_PASSWORD=3211
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USER=icms_app
      - RABBITMQ_PASSWORD=3211
      - DOWNLOADER_MOUNT_POINT=./
      - QUEUE_DOWNLOADER_NAME=icms.downloader
      - QUEUE_IMPORTER_NAME=icms.importer
      - QUEUE_CPMS_NAME=icms.cpms
      - QUEUE_SCHEDULER_STORED_JOB_INIT_NAME=icms.scheduler-stored-job-init
      - QUEUE_SCHEDULER_RESPONSE_NAME=icms.scheduler-response
      - LOG_LEVEL=debug
    depends_on:
      - postgres
      - migrations
      - rabbitmq
    networks:
      - icms-network


  web-backend:
    build:
      context: ./web-backend
      dockerfile: Dockerfile
    environment:
      #      - DB_URL=jdbc:postgresql://host.docker.internal:5432/icms_db
      - DB_URL=jdbc:postgresql://postgres:5432/icms_db
      - DB_USER=icms_app
      - DB_PASSWORD=3211
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USER=icms_app
      - RABBITMQ_PASSWORD=3211
      - WEB_BACKEND_PORT=9000
      - LOG_LEVEL=debug
      - QUEUE_SCHEDULER_STORED_JOB_INIT_NAME=icms.scheduler-stored-job-init
    depends_on:
      - postgres
      - migrations
      - rabbitmq
    ports:
      - "9000:9000"
    networks:
      - icms-network

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: icms_db
      POSTGRES_USER: icms_app
      POSTGRES_PASSWORD: 3211
#    volumes:
#      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - icms-network

  migrations:
    build:
      context: ./migrations
      dockerfile: Dockerfile
    environment:
      #      - DB_URL=jdbc:postgresql://host.docker.internal:5432/icms_db
      - DB_URL=jdbc:postgresql://postgres:5432/icms_db
      - DB_USER=icms_app
      - DB_PASSWORD=3211
    depends_on:
      - postgres
    networks:
      - icms-network


  frontend:
    build:
      context: ./web-frontend
      dockerfile: Dockerfile
    ports:
      - "8080:5173"
    volumes:
      - ./web-frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    networks:
      - icms-network

  rabbitmq:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: icms_app
      RABBITMQ_DEFAULT_PASS: 3211
    ports:
      - "5672:5672" # AMQP protocol
      - "15672:15672" # Management UI
    networks:
      - icms-network

volumes:
  shared_files:
#  postgres_data:

networks:
  icms-network:
    driver: bridge
